---
title: "Year2015"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE)
library(data.table)
library(stringr)
library(splitstackshape)
library(pdftools)
```

```{r}
source("Extract2015.R")

SL_PE_2015<-pdf_text("PresidentialElections2015.pdf")

# all pages----
pages<-c(1:111)
# pages with only one table and excluding them----
pages<-pages[-c(1,10,18,31,48,58,61,64,70,82,87,90,96,99,110,111)]

# creating an empty data list----
Election2015<-NULL

# using iterative method to fill this list with above selected pages----
for (i in pages) 
{
  Election2015[[i]]<-Extract_twotable(i)        
}

# pages with only one table----
pages<-c(10,18,31,48,58,61,64,70,82,87,90,96,99,110)

# using iterative method to fill this list with above selected pages----
for (i in pages) 
        {
        Election2015[[i]]<-Extract_onetable(i)        
        }

# The Final of all tables----
Election2015<-do.call("rbind",Election2015)

Election2015$Electorate<-as.character(Election2015$Electorate)
Election2015[Election2015=="Final District Votes"]<-"Final District Result"
Election2015$Electorate<-as.factor(Election2015$Electorate)

ElecFinal2015<-subset(Election2015,Electorate=="Final District Result" & ColNames=="Maithripala Sirisena")
ElecFinal2015[,sum(Votes),by="ColNames"]

ElecFinal2015<-subset(Election2015,Electorate=="Final District Result" & ColNames=="Mahinda Rajapaksa")
ElecFinal2015[,sum(Votes),by="ColNames"]
```

